name: Generate pact and publish on push
on:
  push:
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://pact.dsch.build
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  generate-contracts:
    runs-on: jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: mvn compile test-compile
      - name: Test
        run: make pact
      - name: Publish contracts
        run: GIT_BRANCH=${GIT_REF:11} make publish_pacts

#  can-i-deploy:
#    runs-on: jdk11
#    needs: generate-contracts
#    steps:
#      - uses: actions/checkout@v2
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Can I deploy?
#        run: GIT_BRANCH=${GITHUB_REF:11} make can_i_deploy
#
#  record_deployment:
#    runs-on: jdk11
#    needs: can-i-deploy
#    steps:
#      - uses: actions/checkout@v2
#      - run: docker pull pactfoundation/pact-cli:latest
#      - name: Record deployment
#        run: GIT_BRANCH=${GITHUB_REF:11} make record_deployment
##        if: github.ref == 'refs/heads/master'
